ALTER TABLE `departments` CHANGE `branch` `branch` INT(11) UNSIGNED NULL DEFAULT NULL;
ALTER TABLE `departments` ADD FOREIGN KEY (`branch`) REFERENCES `branches`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;


ALTER TABLE `employees` CHANGE `department` `department` INT(11) UNSIGNED NULL DEFAULT NULL;
ALTER TABLE `employees` ADD FOREIGN KEY (`department`) REFERENCES `departments`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;


ALTER TABLE `income` ADD FOREIGN KEY (`project`) REFERENCES `projects`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `outcome` ADD FOREIGN KEY (`project`) REFERENCES `projects`(`id`) ON DELETE SET NULL ON UPDATE SET NULL;

ALTER TABLE `projects` CHANGE `responsible_employee` `responsible_employee` INT(11) UNSIGNED NOT NULL DEFAULT '1', CHANGE `branch` `branch` INT(11) UNSIGNED NOT NULL DEFAULT '1';
ALTER TABLE `projects` ADD FOREIGN KEY (`client`) REFERENCES `clients`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `projects` ADD FOREIGN KEY (`responsible_employee`) REFERENCES `employees`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT; ALTER TABLE `projects` ADD FOREIGN KEY (`branch`) REFERENCES `branches`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;